require 'artoo/commands/install'

task :default => :install_commands

task :install_commands do
  @install = Artoo::Commands::Install.new
  puts "INSTALLING ARTOO LITTLEWIRE!!!"
  @install.command(File.expand_path(File.dirname(__FILE__) + "/../lib/artoo/commands/littlewire.rb"))
  @install.command(File.expand_path(File.dirname(__FILE__) + "/../lib/artoo/commands/deps/49-micronucleus.rules"))
  @install.command(File.expand_path(File.dirname(__FILE__) + "/../lib/artoo/commands/deps/littlewireLoader_v13"))
end
