require 'artoo/commands/install'

task :default => :install_commands

task :install_commands do
  @install = Artoo::Commands::Install.new
  @install.command(File.expand_path(File.dirname(__FILE__) + "/../lib/artoo/commands/digispark.rb"))
end
